config/routes.rb
Rails.application.routes.draw do

resources :products do
resources  :reviews
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

      def index
        @products = Product.all
      end


      def new
        @product = Product.new
      end

      def create
        @product = Product.new

         @product.name = params[:product][:name]
         @product.description = params[:product][:description]
         @product.url = params[:product][:url]
         @product.price_in_cents = params[:product][:price_in_cents]


       if  @product.save
            flash[:notice] = "Product successful added!"
            redirect_to products_path
         else
           render :new
       end
      end


      def show
        @product= Product.find(params[:id])
        @review = Review.new
        @reviews= @product.reviews
      end



      def edit
        @product = Product.find(params[:id])
      end

      def update
          @product = Product.find(params[:id])


         @product.name = params[:product][:name]
         @product.description = params[:product][:description]
         @product.url = params[:product][:url]
         @product.price_in_cents = params[:product][:price_in_cents]

         if  @product.save
              flash[:success] = "Product successful updated!"
              redirect_to product_path(@product)
           else
             render :edit
         end

      end

      def destroy
         @product       = Product.find(params[:id])
         @product.destroy
         flash[:success] = "Product successfully deleted!"
         redirect_to root_url

      end




end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController


  def create
    @review = Review.new

     @review.name = params[:review][:name]
     @review.message = params[:review][:message]
     @review.rating = params[:review][:rating]
     @review.product_id = params[:product_id]


     if @review.save
        flash[:success] = "review successful added!"
        redirect_to product_path(params[:product_id])
     else
       redirect_to product_path(params[:product_id])
     end
  end


  def edit
    @review = Review.find(params[:id])
  end


  def destroy
     @review = Review.find(params[:id])
     @review.delete
     flash[:notice] = "review successfully deleted!"
     redirect_to product_path(params[:product_id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <title>Yasuni</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    <p><%= link_to("Add new product", new_product_path) %></p>
  <div class="logo">
    <%=image_tag("logo.png") %>
  </div>


  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_forms.html.erb
<% if product.errors.any? %>

    <ul>
    <% product.errors.full_messages.each do |msg| %>
      <span class="error">*<%= msg %></span>
    <% end %>
    </ul>
<% end %>





<%=form_for product do |f| %>

<p>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :price_in_cents %><br>
  <%= f.text_field :price_in_cents %>
</p>

<p>
  <%= f.label :description %><br>
  <%= f.text_field :description %>
</p>


<p>
  <%= f.label :url %><br>
  <%= f.text_field :url %>
</p>

<p>
   <%= f.submit "Save" %>
 </p>

 <% end %>

app/views/products/edit.html.erb
<h1>edit</h1>

<%= render 'forms', product:@product %>

app/views/products/index.html.erb
<div class="index">


<% @products.each do |product| %>
<ul>
<li><%= product.name %></li>
<li><%=link_to(image_tag(product.url),"/products/#{product.id}")%></li>
<li>Price:<%=product.price_in_cents %> cents</li>
<p>Description:<%=product.description %></p>
<hr>
</ul>


<% end %>

</div>

app/views/products/new.html.erb
<h1>New</h1>

<%= render 'forms', product:@product %>

<%= link_to("Back", products_path) %>

app/views/products/show.html.erb
<% if flash[:notice] %>
<div class="flash"><%= flash[:notice] %></div>
<% end %>




<img src="<%= @product.url %>" alt="@product.id"> <br>
<h4>Desription</h4>
<p><%= @product.name %></p>
<p><%= @product.price_in_cents %></p>
<p><%= @product.description %></p>


<div class="edit_delete">
<%= link_to("Edit", "/products/#{@product.id}/edit") %> <%= link_to("Delete", "/products/#{@product.id}", method: :delete, data: {confirm: "Are you sure you want to delete this picture?"})  %> </p>
</div>

<%= render 'reviews/forms_review', review:@review, product:@product %>

<div class="reviews">
  <h2>Reviews</h2>
  <%@reviews.each do |review| %>
  <uL>
  <p>Name:<%=review.name %></p>
  <p>Rating:<%=review.rating %></p>
  <p>Review:<%=review.message %></p>
  <p><%= link_to("Delete", product_review_path(@product.id, review.id), method: :delete, data: {confirm: "Are you sure you want to delete this review?"}) %></p>
  </ul>
  <% end%>
</div>

app/views/reviews/_forms_review.html.erb
<%=form_for [product, review] do |f| %>

<p>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :message %><br>
  <%= f.text_field :message %>
</p>

<p>
  <%= f.label :rating %>(1-to-5)<br>
  <%= f.text_field :rating %>

  <p>
     <%= f.submit "Submit Review" %>
   </p>

   <% end %>
</p>